language: julia
os:
  - linux
julia:
  - nightly
notifications:
  email: false
git:
  depth: 99999999
cache:
  timeout: 1000
  directories:
    - downloads
env:
  global:
    - BINARYBUILDER_DOWNLOADS_CACHE=downloads
    - BINARYBUILDER_AUTOMATIC_APPLE=false
sudo: required

# Before anything else, get the latest versions of things
before_script:
  - julia -e 'Pkg.clone("https://github.com/JuliaPackaging/BinaryProvider.jl")'
  - julia -e 'Pkg.clone("https://github.com/JuliaPackaging/BinaryBuilder.jl"); Pkg.build()'

script:
  - julia build_tarballs.jl
  
deploy:
    provider: releases
    api_key:
        # Note; this api_key is only valid for JuliaDatabases/MySQLBuilder; you need
        # to make your own: https://docs.travis-ci.com/user/deployment/releases/
        secure: vo/Tbg4spQ8vpXGIlRBXo6XGJgnAVrZpcX2RNluyHt4gu9rjM2jzvsKGSZr7e8x7y/wYQyMuPJEzFXTxArQkk1RNXVhx/bZsF7NAmJYA8a/2Jf0iHO6/CfspKEzsjA0RrXclCSkUZzFy5b5EpqmvZQBpd9KqKN6MQ+qaK+7kS3LEH+uRzQTvxSbj9ru2ugupRqtG2RxjNaVJZAlG3knb4gdxujxXH83DrSPEO4e3Dh9KdL42HeYcq4CHZiihlpajoaKSNM7RMiHXqvs06cgq1KXXYWO0tmyXsO9OgXqTHZOXzJtgQUgErwopZEkaTDZqrav2XVRPD/rOx4vvX+wd6D9SrdcBzpzCSdEsMUICu7hvdDaNLP/2J/+qJ6GFRp7rurvvIRcl52DeeHVFPwsGNDZz8XB5FBonS5MS8Oy5EockqaosPhLpT3MoydUucf1tZXyhuIbH6w/6MU/NChf2B34rK0p2fCLLx5tUf6zPWnOxMLZlFv1gnVWLQWcxBAeHBS3b3PoOckzFaM0syKhgtNEJ8eehtF2Y0LVjXStA0GQVWrKXBHdiumBJlSlURu3oDOrhX+8boKOQUM8n0uPgsf5NTfxH3TfiHLFvy6IZGzSQsEKPNiIGkA0reFVR2jc5XG/FNXsBVOKtZ8AszPw5tNY46LNKOL4H17Jm08EGhkY=
    file_glob: true
    file: products/*
    skip_cleanup: true
    on:
        repo: JuliaDatabases/MySQLBuilder
        tags: true
